# Global configuration
global:
  smtp_smarthost: 'smtp.example.com:587'
  smtp_from: 'vijayakumar2652001@gmail.com'
  smtp_auth_username: 'vijayakumar2652001@gmail.com'
  smtp_auth_password: 'fexz abiu ofwz ccrx'

# Define the route for alert delivery
route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'web.hook'  # Default receiver is web.hook

# Define the receivers
receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://127.0.0.1:5001/'
  - name: 'email'
    email_configs:
      - to: 'vijayakumar2652001@gmail.com'
        send_resolved: true

# Inhibit rule for severity levels
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
