# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - '54.208.150.44:9093'  # Address of your Alertmanager

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "alertrules.yml"  # Ensure this file exists and has the alert rules

# Global configuration
global:
  scrape_interval: 15s  # Set the scrape interval globally (15 seconds)
  evaluation_interval: 15s  # Set evaluation interval for alert rules

# Scrape configuration
scrape_configs:

  # Scrape Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ['54.208.150.44:9090']  # Scrape Prometheus metrics

  # Scrape Node Exporter
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['54.208.150.44:9100']  # Target for Node Exporter (make sure port 9100 is correct)

  # Scrape your custom target (vijay192001/dev)
  - job_name: 'vijay192001/dev'
    static_configs:
      - targets: ['54.208.150.44:80']  # Target for your custom service (port 80)
    metrics_path: /metrics  # Ensure your service exposes Prometheus-compatible metrics at this path
    # You might need to customize this path if your service uses a different endpoint for metrics
